name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.1
      with:
        submodules: 'true'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libgtest-dev cmake
        sudo apt-get install libasound2-dev

    - name: Create Build Directory
      run: |
        mkdir build

    - name: run CMake
      uses: threeal/cmake-action@v2.0.0
      with:
        cmake-version: '3.19'  # Adjust to the CMake version you need

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure