name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: scivision/cmake-action@v1
      with:
        cmake-version: '3.21'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake g++ gdb libgtest-dev alsa-utils libasound2-dev

    - name: Build project
      run: |
        mkdir -p build
        cd build
        cmake ..
        make

    - name: Run unit tests
      run: |
        cd build
        ./tests  # Assuming this is your test executable
